### ISSUE TITLE
ImagicalMine Installation syntax error near unexpected token

### ISSUE THREAD

**Issue by PhilipphatePHP7** [ImagicalMine/php-build-scripts#6]
How can I Choose the PHP binary ?
I have only type curl -sL http://get.imagicalmine.net | bash

And haven't anything choosen.
http://prntscr.com/a5q941

bash: line 34: syntax error near unexpected token )' bash: line 34: 1 ) z="PHP_7.0.2_x86_Linux.tar.gz";;'

**Comment by ecoron** [comment]
confirmed, will fix it soon
